[package]
name = "basm-rust-sdk-macros"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["proc-macro"]

[dependencies]
darling = "0.21.1"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["full"] }
