[package]
name = "basm-sdk-community-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.21.1"
proc-macro2 = "1.0.97"
quote = "1.0.40"
serde_json = "1.0.142"
syn = { version = "2.0.104", features = ["full"] }
